# Generated by Django 4.2.16 on 2025-06-11 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        
        migrations.CreateModel(
            name='EntityAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(default=None, max_length=50)),
                ('address', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'entity_address',
                'managed': True,
            },
        ),
    ]
