# Generated by Django 4.2.16 on 2025-10-23 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discrepency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalStatusEnumTable',
            fields=[
                ('approved_status', models.TextField(db_column='Approved_Status', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Approval_Status_Enum_Table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoryScadaMonthSummary',
            fields=[
                ('monthyearid', models.TextField(db_column='MonthYearID', primary_key=True, serialize=False)),
                ('month', models.SmallIntegerField(blank=True, db_column='Month', null=True)),
                ('month_name', models.TextField(blank=True, db_column='Month_Name', null=True)),
                ('year', models.SmallIntegerField(blank=True, db_column='Year', null=True)),
                ('substation', models.TextField(db_column='Substation')),
                ('completely_not_reporting_points', models.SmallIntegerField(blank=True, db_column='Completely_Not_Reporting_Points', null=True)),
                ('no_of_points', models.SmallIntegerField(blank=True, db_column='No_of_Points', null=True)),
                ('created_at', models.DateTimeField(blank=True, db_column='Created_At', null=True)),
                ('category', models.TextField(blank=True, db_column='Category', null=True)),
                ('state', models.TextField(blank=True, db_column='State', null=True)),
                ('completely_not_reporting_points_prevmonth', models.SmallIntegerField(blank=True, db_column='Completely_Not_Reporting_Points_PrevMonth', null=True)),
                ('scada_substation', models.CharField(blank=True, db_column='scada_substation', null=True)),
            ],
            options={
                'db_table': 'History_SCADA_Month_Summary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoryScadaPointSummary',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('monthyearid', models.TextField(db_column='MonthYearID')),
                ('month', models.SmallIntegerField(blank=True, db_column='Month', null=True)),
                ('month_name', models.TextField(blank=True, db_column='Month_Name', null=True)),
                ('year', models.SmallIntegerField(blank=True, db_column='Year', null=True)),
                ('non_availability_percentage', models.SmallIntegerField(blank=True, db_column='Non_Availability_Percentage', null=True)),
                ('non_availability_percentage_prevmonth', models.SmallIntegerField(blank=True, db_column='Non_Availability_Percentage_PrevMonth', null=True)),
                ('created_at', models.DateTimeField(blank=True, db_column='Created_At', null=True)),
                ('status', models.TextField(blank=True, db_column='Status', null=True)),
                ('remarks', models.TextField(blank=True, db_column='Remarks', null=True)),
                ('timeline', models.DateTimeField(blank=True, db_column='TimeLine', null=True)),
                ('approved_status', models.TextField(blank=True, db_column='Approved_Status', null=True)),
                ('iccp_ioa', models.CharField(db_column='ICCP_IOA')),
                ('substation', models.CharField(db_column='Substation')),
                ('admin_remarks', models.TextField(blank=True, db_column='Admin_Remarks', null=True)),
                ('admin_createdtime', models.DateTimeField(blank=True, db_column='Admin_Createdtime', null=True)),
                ('master_seq_id', models.IntegerField(blank=True, db_column='master_seq_id', null=True)),
                ('master_point_name', models.TextField(blank=True, db_column='master_point_name', null=True)),
            ],
            options={
                'db_table': 'History_SCADA_Point_Summary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScadaPointNameRequestsAndApprovalHistory',
            fields=[
                ('requestid', models.BigAutoField(db_column='RequestId', primary_key=True, serialize=False)),
                ('userid', models.TextField(blank=True, db_column='UserId', null=True)),
                ('monthyearid', models.TextField(blank=True, db_column='MonthYearID', null=True)),
                ('point_name', models.TextField(blank=True, db_column='Point_Name', null=True)),
                ('remarks', models.TextField(blank=True, db_column='Remarks', null=True)),
                ('userrequestcreatedat', models.DateTimeField(blank=True, db_column='UserRequestCreatedAt', null=True)),
                ('approved_remarks', models.TextField(blank=True, db_column='Approved_Remarks', null=True)),
                ('approvalcreatedat', models.DateTimeField(blank=True, db_column='ApprovalCreatedAt', null=True)),
                ('timeline', models.DateTimeField(blank=True, db_column='TimeLine', null=True)),
                ('status', models.TextField(blank=True, db_column='Status', null=True)),
                ('approved_status', models.TextField(blank=True, db_column='Approved_Status', null=True)),
                ('admin_remarks', models.TextField(blank=True, db_column='Admin_Remarks', null=True)),
                ('admin_createdtime', models.DateTimeField(blank=True, db_column='Admin_Createdtime', null=True)),
            ],
            options={
                'db_table': 'SCADA_Point_Name_Requests_And_Approval_History',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StateEnumTable',
            fields=[
                ('state', models.TextField(db_column='State', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'State_Enum_Table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatusEnumTable',
            fields=[
                ('status', models.TextField(db_column='Status', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Status_Enum_Table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IntraStateRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utility', models.CharField(default=None, max_length=255)),
                ('type_of_request', models.CharField(default=None, max_length=20)),
                ('end_a_substation', models.CharField(default=None, max_length=255)),
                ('util_sld', models.CharField(blank=True, max_length=255, null=True)),
                ('util_subtop', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'IntraState_Requests',
                'managed': False
            },
        ),
        migrations.CreateModel(
            name='RTUMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(default=None, max_length=255)),
                ('protocol', models.CharField(default=None, max_length=20)),
                ('responsibility', models.CharField(default=None, max_length=255)),
                ('linkMailList', models.TextField(blank=True, default=None, null=True)),
                ('mcc_m', models.CharField(blank=True, max_length=20, null=True)),
                ('mcc_s', models.CharField(blank=True, max_length=20, null=True)),
                ('bcc_m', models.CharField(blank=True, max_length=20, null=True)),
                ('bcc_s', models.CharField(blank=True, max_length=20, null=True)),
                ('rtu_type', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
            options={
                'db_table': 'rtu_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScadaTelemetryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('channel_type', models.CharField(blank=True, max_length=10, null=True)),
                ('mainChannel', models.CharField(blank=True, max_length=200, null=True)),
                ('mainOutageTime', models.DateTimeField(blank=True, max_length=200, null=True)),
                ('mainChannelStatus', models.CharField(blank=True, max_length=255, null=True)),
                ('standByChannel', models.CharField(blank=True, max_length=200, null=True)),
                ('standByOutageTime', models.DateTimeField(blank=True, max_length=200, null=True)),
                ('standByChannelStatus', models.CharField(blank=True, max_length=255, null=True)),
                ('mainactionNeeded', models.CharField(blank=True, max_length=500, null=True)),
                ('standbyactionNeeded', models.CharField(blank=True, max_length=500, null=True)),
                ('createdDate', models.DateField(auto_now_add=True, null=True)),
                ('mail_sent', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'db_table': 'scada_telemetry_report',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubstationList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substation_name', models.CharField(default=None, max_length=255)),
                ('voltage_level', models.IntegerField(default=None)),
            ],
            options={
                'db_table': 'substation_list',
                'managed': True,
                'unique_together': {('substation_name', 'voltage_level')},
            },
        ),
        migrations.CreateModel(
            name='ScadaPointNameMappingHistory',
            fields=[
                ('State', models.TextField(blank=True, db_column='State', null=True)),
                ('Substation', models.TextField(blank=True, db_column='Substation', null=True)),
                ('Substation_Name', models.TextField(blank=True, db_column='Substation_Name', null=True)),
                ('Voltage_Level', models.SmallIntegerField(blank=True, db_column='Voltage_Level', null=True)),
                ('ELEMENT_DESCRIPTION', models.TextField(blank=True, db_column='ELEMENT_DESCRIPTION', null=True)),
                ('ELEMENT_CATEGORY', models.TextField(blank=True, db_column='ELEMENT_CATEGORY', null=True)),
                ('Metric_Type', models.TextField(blank=True, db_column='Metric_Type', null=True)),
                ('Point_Name', models.TextField(db_column='Point_Name')),
                ('IOA', models.SmallIntegerField(blank=True, db_column='IOA', null=True)),
                ('ICCP_Name', models.TextField(blank=True, db_column='ICCP_Name', null=True)),
                ('Part_Of_Island_Scheme', models.TextField(blank=True, db_column='Part_Of_Island_Scheme', null=True)),
                ('ot_type', models.TextField(blank=True, db_column='ot_type', null=True)),
                ('seq_id', models.IntegerField(db_column='seq_id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'staging.SCADA_Point_Name_Mapping',
                'unique_together': {('seq_id', 'Point_Name')},
                'managed': False
            },
        ),
        migrations.CreateModel(
            name='ScadaPointNameMapping',
            fields=[
                ('State', models.TextField(blank=True, db_column='State', null=True)),
                ('Substation', models.TextField(blank=True, db_column='Substation', null=True)),
                ('Substation_Name', models.TextField(blank=True, db_column='Substation_Name', null=True)),
                ('Voltage_Level', models.SmallIntegerField(blank=True, db_column='Voltage_Level', null=True)),
                ('ELEMENT_DESCRIPTION', models.TextField(blank=True, db_column='ELEMENT_DESCRIPTION', null=True)),
                ('ELEMENT_CATEGORY', models.TextField(blank=True, db_column='ELEMENT_CATEGORY', null=True)),
                ('Metric_Type', models.TextField(blank=True, db_column='Metric_Type', null=True)),
                ('Point_Name', models.TextField(db_column='Point_Name')),
                ('IOA', models.SmallIntegerField(blank=True, db_column='IOA', null=True)),
                ('ICCP_Name', models.TextField(blank=True, db_column='ICCP_Name', null=True)),
                ('Part_Of_Island_Scheme', models.TextField(blank=True, db_column='Part_Of_Island_Scheme', null=True)),
                ('ot_type', models.TextField(blank=True, db_column='ot_type', null=True)),
                ('seq_id', models.IntegerField(db_column='seq_id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'SCADA_Point_Name_Mapping',
                'unique_together': {('seq_id', 'Point_Name')},
                'managed': False
            },
        ),
        migrations.CreateModel(
            name='RTUReportMessageCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_no', models.IntegerField(default=None)),
                ('month', models.CharField(blank=True, max_length=10, null=True)),
                ('year', models.IntegerField(default=None)),
            ],
            options={
                'db_table': 'rtu_message_count',
                'managed': False,
                'unique_together': {('month', 'year', 'message_no')},
            },
        ),
        migrations.CreateModel(
            name='IntraStateElements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_type', models.CharField(default=None, max_length=50)),
                ('element_no', models.IntegerField(default=None)),
                ('no_of_bays', models.IntegerField(default=None)),
                ('name_of_element', models.CharField(default=None, max_length=255)),
                ('date_of_charging', models.DateField(default=None)),
                ('end_b_substation', models.CharField(default=None, max_length=255)),
                ('element_sld', models.CharField(blank=True, max_length=255, null=True)),
                ('element_subtop', models.CharField(blank=True, max_length=255, null=True)),
                ('element_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='discrepency.intrastaterequests')),
            ],
            options={
                'db_table': 'IntraState_Elements',
                'managed': False
            },
        ),
    ]
