# Generated by Django 4.2.16 on 2025-10-23 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discrepency', '0002_approvalstatusenumtable_historyscadamonthsummary_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intrastateelements',
            options={},
        ),
        migrations.AlterModelOptions(
            name='intrastaterequests',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rtumaster',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='rtureportmessagecount',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='scadapointnamemapping',
            options={},
        ),
        migrations.AlterModelOptions(
            name='scadapointnamemappinghistory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='scadatelemetryreport',
            options={'managed': True},
        ),
    ]
