# Generated by Django 4.2.16 on 2025-12-02 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discrepency', '0003_alter_intrastateelements_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intrastaterequests',
            name='util_oag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scadapointnamemappinghistory',
            name='remc_element_type',
            field=models.TextField(blank=True, db_column='"remc_element_type"', null=True),
        ),
        migrations.AlterField(
            model_name='scadapointnamemappinghistory',
            name='ELEMENT_CATEGORY',
            field=models.TextField(blank=True, db_column='"ELEMENT_CATEGORY"', null=True),
        ),
        migrations.AlterField(
            model_name='scadapointnamemappinghistory',
            name='ELEMENT_DESCRIPTION',
            field=models.TextField(blank=True, db_column='"ELEMENT_DESCRIPTION"', null=True),
        ),
        migrations.AlterField(
            model_name='scadapointnamemappinghistory',
            name='ICCP_Name',
            field=models.TextField(blank=True, db_column='"ICCP_Name"', null=True),
        ),
        migrations.AlterField(
            model_name='scadapointnamemappinghistory',
            name='IOA',
            field=models.SmallIntegerField(blank=True, db_column='"IOA"', null=True),
        ),
        migrations.AlterField(
            model_name='scadapointnamemappinghistory',
            name='Metric_Type',
            field=models.TextField(blank=True, db_column='"Metric_Type"', null=True),
        ),
        migrations.AlterField(
            model_name='scadapointnamemappinghistory',
            name='Part_Of_Island_Scheme',
            field=models.TextField(blank=True, db_column='"Part_Of_Island_Scheme"', null=True),
        ),
        migrations.AlterField(
            model_name='scadapointnamemappinghistory',
            name='Point_Name',
            field=models.TextField(db_column='"Point_Name"'),
        ),
        migrations.AlterField(
            model_name='scadapointnamemappinghistory',
            name='State',
            field=models.TextField(blank=True, db_column='"State"', null=True),
        ),
        migrations.AlterField(
            model_name='scadapointnamemappinghistory',
            name='Substation',
            field=models.TextField(blank=True, db_column='"Substation"', null=True),
        ),
        migrations.AlterField(
            model_name='scadapointnamemappinghistory',
            name='Substation_Name',
            field=models.TextField(blank=True, db_column='"Substation_Name"', null=True),
        ),
        migrations.AlterField(
            model_name='scadapointnamemappinghistory',
            name='Voltage_Level',
            field=models.SmallIntegerField(blank=True, db_column='"Voltage_Level"', null=True),
        ),
        migrations.AlterField(
            model_name='scadapointnamemappinghistory',
            name='ot_type',
            field=models.TextField(blank=True, db_column='"ot_type"', null=True),
        ),
        migrations.AlterField(
            model_name='scadapointnamemappinghistory',
            name='seq_id',
            field=models.IntegerField(db_column='"seq_id"', primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='scadapointnamemappinghistory',
            table='"staging"."SCADA_Point_Name_Mapping"',
        ),
    ]
